### ISSUE TITLE
"attempt to include relative file name but could not determine base dir"

### ISSUE THREAD

**Issue by xerz-one** [jerry40/guile-kernel#10]
Using Guile 3.0.0, the following error comes up when trying to start a Guile kernel

```
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /home/user/.local/share/jupyter/kernels/guile/guile-jupyter-kernel.scm
;;; WARNING: compilation of /home/user/.local/share/jupyter/kernels/guile/guile-jupyter-kernel.scm failed:
;;; attempt to include relative file name but could not determine base dir
Backtrace:
           6 (primitive-load "/home/user/.local/share/jupyter/kernels/guil…")
In ice-9/eval.scm:
   721:20  5 (primitive-eval (include "tools.scm"))
In ice-9/psyntax.scm:
  1241:36  4 (expand-top-sequence ((include "tools.scm")) _ _ #f _ _ _)
  1133:20  3 (parse _ (("placeholder" placeholder)) ((top) #(# # …)) …)
  1354:32  2 (syntax-type (include "tools.scm") (("placeholder" #)) # …)
  1565:32  1 (expand-macro #<procedure 7f1db6f8bae0 at ice-9/psynta…> …)
  3254:24  0 (_ _ _ #:dirname _)
```

**Comment by xerz-one** [comment]
I believe this to be a specific issue with Guile and unrelated to guile-kernel, but I'm leaving it here in case I find a helpful solution.

**Comment by jerry40** [comment]
Thanks! Will try to figure it out, interesting.

**Comment by xerz-one** [comment]
Hey there, I think I have just figured it out! Guile seemingly doesn't automatically add the script directory's path to the load path, so it has to be done manually with something like the environment variable `GUILE_LOAD_PATH`. Here's an example, assuming you're currently in the kernel path:
 
```
$ GUILE_LOAD_PATH=$PWD guile -c '(display %load-path) (newline)'
(/app/.local/share/jupyter/kernels/guile /app/.local/share/guile/3.0 /app/.local/share/guile/site/3.0 /app/.local/share/guile/site /app/.local/share/guile)
```

According to https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs, this can be set using a `env` dictionary, like the following:

```json
"env": {"GUILE_LOAD_PATH": "/app/.local/share/jupyter/kernels/guile"},
```

**Comment by xerz-one** [comment]
Hmm, that did *not* fix it. I'm new to Guile so I'm sorry if I'm not being very helpful, but for now this is as far as I got.

Furthermore, [the official Guile documentation](https://www.gnu.org/software/guile/manual/html_node/Local-Inclusion.html#index-include) reports that "*If file-name is a relative path, it is searched for relative to the path that contains the file that the include form appears in.*"

**Comment by jerry40** [comment]
What is your operating system and what is the kernel location?

**Comment by jerry40** [comment]
Yes I noticed it too... Apparently if we change `(include "tools.scm")` to `(include "./tools.scm")` it should work, or I do not understand it well enough

**Comment by xerz-one** [comment]
The system is Ubuntu 16.04.6, with a manually compiled Guile 3.0.0. The kernel path is `$HOME/.local/share/jupyter/kernels/guile`, with the contents of the directory being

`guile-jupyter-kernel.scm  hmac.scm  kernel.json  tools.scm`

and `kernel.json` looks like

```json
{
    "env": {"GUILE_LOAD_PATH": "/app/.local/share/jupyter/kernels/guile"},
    "argv": ["guile", "-s",
             "/app/.local/share/jupyter/kernels/guile/guile-jupyter-kernel.scm",
             "--", "{connection_file}"],
    "display_name": "Guile",
    "language": "scheme"
}
```

although the issue can be reproduced from the terminal with `GUILE_LOAD_PATH=/app/.local/share/jupyter/kernels/guile guile -s /app/.local/share/jupyter/kernels/guile/guile-jupyter-kernel.scm`

**Comment by xerz-one** [comment]
hmm, changing `include` into `include-from-path` without any further changes seems to fix it, no `GUILE_LOAD_PATH` required

**Comment by jerry40** [comment]
It is a strange behaviour of guile3.0 to be honest. Perhaps it can be reported as an issue. I doubt no one did not notice this though.

**Comment by jerry40** [comment]
May you try this form please? `(include "./tools.scm")`

**Comment by xerz-one** [comment]
Doesn't work, instead `(include-from-path "tools.scm")` does, although it needs to be executed on the kernel path the first time? (and I can sucesfully do notebooks and run code from them!)

**Comment by xerz-one** [comment]
Somehow I'm now getting `/app/.local/share/jupyter/kernels/guile/guile-jupyter-kernel.scm:7:19: include-from-path: file not found in path in subform "tools.scm" of (include-from-path "tools.scm")`. I wonder if there is any environment (nothing I touched there) or compilation (I used `CFLAGS="-Os"`) issue.

**Comment by jerry40** [comment]
May you try using include-from-path with full path to the file?

**Comment by jerry40** [comment]
And include with full path too

**Comment by xerz-one** [comment]
Full path `include` and `include-from-path` do work! There is _something_ messed up with importing from relative paths, but I can't tell what - and shipping with an absolute path is definitely not ideal.

**Comment by jerry40** [comment]
Great! I only hope it is a bug in the version 3.0 or I just do not understand how it should work.

**Comment by jerry40** [comment]
Hi @espectalll , I changed `include` to `load` and it seems to be working, can you test the kernel again please?

**Comment by xerz-one** [comment]
The issue no longer happens! Yeah, this can be considered as solved.
