### ISSUE TITLE
output not displayed

### ISSUE THREAD

**Issue by xerz-one** [jerry40/guile-kernel#11]
Writing a cell with:

```scheme
(display "Hey!")
```

returns no output. Same happens when running from a console.

Equally, doing any successful operation, like `(define x 42)`, does not return any output - however, `(error "Fail!")` does work.

**Comment by jerry40** [comment]
OMG, perhaps I need to install that version and play with it, it is really
bizarre

**Comment by xerz-one** [comment]
Ah yes, should point out this is done with Guile 3.0.0. Keep in mind it **is** a major version, with new features enabled by default like JIT compilation.

**Comment by jerry40** [comment]
Can't reproduce it on the kernel using `guile (GNU Guile) 3.0.0.23-7dc90`

**Comment by xerz-one** [comment]
OK, so I decided to reinstall everything, and... I must be building `libiconv` wrong (I have to in the setup I'm using) because I'm getting this unrelated error now

```
ERROR: In procedure read-char:
In procedure open_iconv_descriptors: invalid or unknown character encoding UTF8
```

Can't debug further right now, but I'll take a look as soon as possible - this specific issue is very likely my fault, so I'm not opening up a ticket for it.

**Comment by ntoxeg** [comment]
This is still a problem for me, errors are displayed but normal output not, it's with Guile 2.2 on Ubuntu 20.04.

**Comment by ntoxeg** [comment]
Correction! This is a problem in **Jupyter Lab** specifically.
