### ISSUE TITLE
Refactor kernel

### ISSUE THREAD

**Issue by xerz-one** [jerry40/guile-kernel#13]
Currently, the kernel code is manually installed by copying the contents of `src` into `$JUPYTER_PATH/kernels/guile` and replacing the absolute path of `guile-jupyter-kernel.scm` inside `kernel.json`. Ideally, a Jupyter kernel should be able to run without making any changes to the source code, thus the project should be refactored accordingly, providing a Makefile or some similar installation script.

The best choice imho would be providing the kernel script as a Guile module. Additionally, I have looked into including the Jupyter path relative variable into `kernel.json`, but [jupyter/jupyter_client](https://github.com/jupyter/jupyter_client) provides no way to add in variables other than `connection_file`. Perhaps looking into how [`guix-kernel`](https://gitlab.inria.fr/guix-hpc/guix-kernel) does it could be helpful?

**Comment by xerz-one** [comment]
Actually, it's clear this project is duplicating efforts over those of `guix-kernel`. Could be worth talking with Ludovic Courtès.

**Comment by jerry40** [comment]
It is easier to use Dockerfile to avoid these issues.
