### ISSUE TITLE
Error in procedure number->string: Wrong type argument in position 1: #f

### ISSUE THREAD

**Issue by ntoxeg** [jerry40/guile-kernel#14]
The following error happens when I try to start the kernel on a Ubuntu 20.04 Docker container with Guile 2.2:

```
Backtrace:

7 (apply-smob/1 #<catch-closure 561b1a524880>)

In ice-9/boot-9.scm:

705:2 6 (call-with-prompt _ _ #<procedure default-prompt-handle…>)

In ice-9/eval.scm:

619:8 5 (_ #(#(#<directory (guile-user) 561b1a5ac140>)))

2312:4 4 (save-module-excursion _)

3832:12 3 (_)

In /usr/local/share/jupyter/kernels/guile-kernel/src/guile-jupyter-kernel.scm:

50:23 2 (_)

44:96 1 (create-address #f)

In unknown file:

0 (number->string #f #<undefined>)


ERROR: In procedure number->string:

In procedure number->string: Wrong type argument in position 1: #f
```

**Comment by jerry40** [comment]
Thanks! Will try to reproduce it on my side.

**Comment by jerry40** [comment]
I tried to run docker image with quile-2.2 (debian) and Docker version 19.03.5 and for me it works..
What I did:
1. changed Dockerfile for using guile-2.2
```
RUN apt-get update && apt-get install -y \
    guile-2.2-dev guile-2.2 automake gcc libunwind-dev
```
2.  `sudo docker build .`
3.  `sudo docker images`  --found the newest ID there _ID_
4. `sudo docker run -p8888:8888 _ID_`
5. opened URL which can be found in terminal - http://127.0.0.1:8888/?token=21b98634db....
6. created jupyter guile session and tried to execute a command

and it worked.

Can you describe how did you met a problem step by step please?

**Comment by ntoxeg** [comment]
All right, the Dockerfile I was working with had an old version of `guile-json`, this issue is solved.
