### ISSUE TITLE
Error if the last line of a cell has code with a comment

### ISSUE THREAD

**Issue by ntoxeg** [jerry40/guile-kernel#15]
If I have a cell where the last line has some code with a comment at the end I get that kind of error:
```
read-error
(scm_i_lreadparen #<unknown port>:2:148: end of file () #f)
```

**Comment by jerry40** [comment]
Got it, I wrap code block into 
``` 
(begin _code_block_ )
```
so comments hide the last `)`
I will fix it soon.
Thanks!

**Comment by jerry40** [comment]
Fixed, may you test it again please?

**Comment by ntoxeg** [comment]
The bug is indeed gone, thanks.
