### ISSUE TITLE
Standard output not displayed in Jupyter Lab

### ISSUE THREAD

**Issue by ntoxeg** [jerry40/guile-kernel#16]
Similar to #11 but only happens in Jupyter Lab.

**Comment by jerry40** [comment]
I tried it and for me it does not return execution results at all. Jupyter Lab seems to be working in different way, I need to look at it. I will return when I found a problem's root

**Comment by jerry40** [comment]
Hi! I fixed the problem, can you test jupyterlab with the kernel again please?

**Comment by ntoxeg** [comment]
I'm getting the following error and the kernel keeps restarting.

```
 ERROR: In procedure number->string:
In procedure number->string: Wrong type argument in position 1: #f
[I 15:03:12.684 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Backtrace:
           7 (apply-smob/1 #<catch-closure 56248d4a0880>)
 In ice-9/boot-9.scm:
    705:2  6 (call-with-prompt ("prompt") #<procedure 56248d4b59e0 …> …)
 In ice-9/eval.scm:
     619:8  5 (_ #(#(#<directory (guile-user) 56248d529140>)))
 In ice-9/boot-9.scm:
    2312:4  4 (save-module-excursion #<procedure 56248d4d5330 at ice-…>)
   3832:12  3 (_)
 In /usr/local/share/jupyter/kernels/guile-kernel/src/guile-jupyter-kernel.scm:
     50:23  2 (_)
     44:96  1 (create-address #f)
 In unknown file:
            0 (number->string #f #<undefined>)
```

**Comment by jerry40** [comment]
Hm... I can't reproduce the error on my side. It looks like the kernel can't parse jupyter's json file which keeps ports information. A path to this file should be a kernel input parameter. Interesting
```
{
  "shell_port": 40773,
  "signature_scheme": "hmac-sha256",
  "ip": "127.0.0.1",
  "kernel_name": "guile",
  "transport": "tcp",
  "iopub_port": 39695,
  "hb_port": 55171,
  "stdin_port": 49165,
  "control_port": 57521,
  "key": "..."
}
```

**Comment by ntoxeg** [comment]
It turned out I was using my old Dockerfile and had old `guile-json` installed. Now everything seems to be okay. Thanks for the fix!

**Comment by jerry40** [comment]
Great, thanks!
