### ISSUE TITLE
Editing  guile-simple-zmq

### ISSUE THREAD

**Issue by joejnke** [jerry40/guile-kernel#3]
How can i increase BUF-SIZE in guile-simple-zmq?
appreciate if any one can give a procedure for doing that.

**Comment by jerry40** [comment]
Hi! Do you get large zmq messages and want to increase performance? 

You can test different BUF-SIZE values just by editing it in simple-zmq.scm. Do not forget to restart guile-kernel after that,

If you want to do it from your code, I can add new function, something like 'zmq-set-buffer-size' to guile-simple-zmq.

**Comment by jerry40** [comment]
Added functions
```
(define (zmq-get-buffer-size)
  BUF-SIZE)

(define (zmq-set-buffer-size new-size)
  "Change a buffer size, affects the zmq-get-msg-parts function"
  (set! BUF-SIZE new-size))
```

to simple-zmq.scm

**Comment by TENSAE21** [comment]
Hey @jerry40 just wanted to mention that the link for the wget (for simple-zmq) should be https://raw.githubusercontent.com/jerry40/guile-simple-zmq/master/src/simple-zmq.scm, the current one downloads it as an HTML file

**Comment by jerry40** [comment]
Hi @TENSAE21 ! Thank you very much, I fixed it.

**Comment by joejnke** [comment]
tnx @jerry40
