### ISSUE TITLE
Kernel crashes if cell start a thread

### ISSUE THREAD

**Issue by andre-senna** [jerry40/guile-kernel#6]
A notebook with this single cells crashes the kernel.

(define (my-func)(while #t (usleep 10)))
(call-with-new-thread my-func (lambda (key . args) #t))

Error log:

Backtrace:
           6 (apply-smob/1 #<catch-closure 1ccbb80>)
In ice-9/boot-9.scm:
    705:2  5 (call-with-prompt _ _ #<procedure default-prompt-handle…>)
In ice-9/eval.scm:
    619:8  4 (_ #(#(#<directory (guile-user) 1d64140>)))
In ice-9/boot-9.scm:
   2312:4  3 (save-module-excursion _)
  3822:12  2 (_)
In /usr/local/share/jupyter/kernels/guile-kernel/src/guile-jupyter-kernel.scm:
   105:18  1 (general-handler #<pointer 0x1bd55d0>)
In simple-zmq.scm:
   418:20  0 (zmq-get-msg-parts-bytevector #<pointer 0x1bd55d0> _)

simple-zmq.scm:418:20: In procedure zmq-get-msg-parts-bytevector:
Throw to key `zmq-error' with args `(4 "Interrupted system call")'.

Some deprecated features have been used.  Set the environment
variable GUILE_WARN_DEPRECATED to "detailed" and rerun the
program to get more information.  Set it to "no" to suppress
this message.

**Comment by jerry40** [comment]
Hi, Andre!

Interesting. The error occures in zmq module which is strange... perhaps usleep is deprecated? I can't check it right now, can you replace usleep with sleep?

**Comment by andre-senna** [comment]
Ji Evgeny! BTW thank you for taking the time to write this kernel and making it public. It's being very very very useful to me. 

And please take your time to check this out... I've just surrounded the offending zmq call with a catch so it is working OK for me. I just raised the issue because I think you might want to know about it.

Yes, zmq crashes, not the kernel itself. But I believe it's because the kernel is making some wrong assumption regarding the shell socket in a multi-thread scenario. In the original code where I noticed this problem I've changed the code to execute in the main thread and it didn't crashed. I mean... The same code run OK when executing in main thread but crashes when executing in a separate thread.

So no matter usleep or sleep, the behavior is exactly the same. However, the probability of crash is larger as the sleeping time is smaller which is a strong scent of a race condition somewhere. (sleep 1) will make above code crash eventually (although not immediately).

**Comment by jerry40** [comment]
I'm glad to know the kernel is being used and it is helpful! Ans thanks for raising the issue, I can reproduce it on my side. Interesting indeed. I'll try to figure out what's happening here...

**Comment by jerry40** [comment]
Ok, I think that I need to try to read from a queue again after zeromq EINTR error occures. Will test it in 1-2 days.

**Comment by jerry40** [comment]
Hi! I merged a pull request where I think the issue is fixed! Can you test it on your side? (you'll need to pull guile-simple-zmq only).

**Comment by andre-senna** [comment]
Hi. I can't see your changes for some bizarre misbehavior of github. It seems like it's unstable somehow (I'm having bizarre behavior in other projects as well). I'll try again later today or tomorrow.

**Comment by jerry40** [comment]
A link to the commit: https://github.com/jerry40/guile-simple-zmq/commit/75bde5019a0f4348dfdbd323e41b041da033d121

**Comment by andre-senna** [comment]
Yes, it works! Thanks a lot!

**Comment by jerry40** [comment]
Glad to hear this! Thanks for your help!
